### ISSUE TITLE
Waypoint Management

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1718]
The current purpose of this ticket is for tracking this missing feature. Lmk on Discord or comment below what you would like to see here and I'll build up a full description and plan over time.

**Comment by DogeTennant** [comment]
These are my suggestions for this feature: (hopefully I'm allowed to comment here lmao)

Keep in mind that the hotkeys I provide are just ideas u could do the hotkeys to anything, that is more comfortable or realizable

Here it is:

- Ability to edit an existing waypoint by clicking on it on the map (LEFT CLICK ON WAYPOINT)
- Ability to delete waypoints by clicking on them on the map (SHIFT+RIGHT CLICK ON WAYPOINT)
- Ability to move waypoints on the map (HOLD LEFT CLICK + DRAG ACROSS THE MAP)
_This feature isn't really vital and I don't mind if it's not added_
- Add the Search Function that's in development for so long.

**Waypoint Management GUI:**

- Add a scrollbar
- Let us change the Group of a waypoint in the edit menu like the icon instead of just on the main management page.
- Let us select multiple waypoints (you can add like boxes on the left-hand side of the waypoint management GUI that you could tick), and let us change groups, icons, visibility, and color of all selected waypoints at once.
- Ability to use "Teleport Waypoint to Player's location" in edit mode

**Comment by kristofbolyai** [comment]
Let's just link the feedback site as I already responded there: https://feedback.wynntils.com/posts/100/let-us-create-edit-move-and-delete-search-waypoints-more-easily
