### ISSUE TITLE
Lootrun Beacon Master dialogue shows in chat too with overlay enabled, after interactions 

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#1726]
![image](https://github.com/Wynntils/Artemis/assets/49001742/155af4f1-18be-49cf-ac14-5ef9fe157024)

**Comment by magicus** [comment]
That is not a bug, but a feature. Otherwise you cannot click on the options.

**Comment by magicus** [comment]
There was a bug claiming that this was not possible, but then I think the reporter misunderstood how this was supposed to work.

(I agree that it is a bit wonky and more of a workaround, but currently we cannot click on an overlay. Dialogues with options should probably be made a Screen instead of an overlay...)

**Comment by magicus** [comment]
It even says so. "Open chat and click on the option to select it". In red. 🤷

**Comment by kristofbolyai** [comment]
I would have to test, but I don't think the message showed up the first time, only after selecting an option, and it reappearing.

**Comment by magicus** [comment]
Then that is a bug. But I doubt that would be the case, I tested this pretty thorough.

**Comment by kristofbolyai** [comment]
This will be fixed with #2356, so I'll close this now.
