### ISSUE TITLE
Qodana code report

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#187]
Qodana code report should be a much better replacement for legacy's Codefactor. 

What do you think? @magicus @P0keDev @Incompleteusern 

Example PR/Report: https://github.com/kristofbolyai/Artemis/pull/1#issuecomment-1200123934

I have tried to embed the report into the comment, but I only could manage to send the link. It should be fine.

**Comment by magicus** [comment]
Qodana also sends warnings with file/line information, which shows up like this:
https://github.com/kristofbolyai/Artemis/commit/fbc445f6b6d32cc892e477868dbab7bb4dac4f84

I think it looks nice; the report itself is probably less useful.

I agree that Qodana looks nice, let's try incorporating it. If it turns out to be a pain in the bum, we can always tweak it (like we had to do with Spotless) or turn it off again.

**Comment by kristofbolyai** [comment]
> Qodana also sends warnings with file/line information, which shows up like this: [kristofbolyai@fbc445f](https://github.com/kristofbolyai/Artemis/commit/fbc445f6b6d32cc892e477868dbab7bb4dac4f84)
> 
> I think it looks nice; the report itself is probably less useful.
> 
> I agree that Qodana looks nice, let's try incorporating it. If it turns out to be a pain in the bum, we can always tweak it (like we had to do with Spotless) or turn it off again.

You can also download the report and with a simple http-server, browse it.
