### ISSUE TITLE
Can't claim rewards from daily objective

### ISSUE THREAD

**Issue by neklas2000** [Wynntils/Wynntils#1918]
### Version

v0.0.3-alpha.234

### Brief Description

Once I completed my daily objective (witnessed it two times with the objective to win a dungeon) I can't claim my reward.
I do get the message in the chat but I can't click on it so that reward screen would show.

### Steps to Reproduce

Complete a daily objective (preferably to win a dungeon since I'm not sure if that's a general issue for all objectives) and try to click on the message in the chat.

### Expected Behaviour

The reward screen should show up

### Actual Behaviour

Nothing happens, no error message, no indication that there's something to click

**Comment by kristofbolyai** [comment]
Use `/daily`, sometimes Wynn resends that message.

**Comment by magicus** [comment]
On a tangent, I have been thinking if there is anything we can do to assist this. Like keep some kind of reminder until you have claimed your award (don't know how many times I forgot since I wanted to dump all my loot in the bank before claiming, and once I got to the city I had completely forgotten about /daily).

And making *something* clickable to call the /daily command. Whatever that something is...
