### ISSUE TITLE
Doesn't work on 1.20.4 although it is noted that it is

### ISSUE THREAD

**Issue by DreenDex** [Wynntils/Wynntils#2268]
I downloaded latest modrinth version for fabric "[Wynntils Artemis (fabric) v0.0.4-beta.83](https://modrinth.com/mod/wynntils/version/j9fh8XyB)" that is marked right now as "for Minecraft 1.20.2-1.20.4".

But Fabric Loader 0.15.1 say:
Replace mod 'Wynntils' (wynntils) 0.0.4-beta.83 with any version that is compatible with: minecraft 1.20.4.

**Comment by Rafii2198** [comment]
Only 1.20.2 is supported. I think there is something off with Modrinth as I noticed many mods being marked for versions they do not support.

**Comment by DreenDex** [comment]
@Rafii2198 First, this should not be the way to go. True reason of this problem should be found and eliminated because people lose time trying _broken_ mods and developers get paid for downloads.

Second, I just tested latest-to-the-moment fabric version of Wynntils on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/wynntils/files/4935278). It has same problem. Marked as "1.20.2, 1.20.3", but works only on 1.20.2.

EDIT: Not exactly "_broken_" mods, but theirs compatibility for the base game version is described incorrectly on their download page.

**Comment by Rafii2198** [comment]
I have a feeling it has something to do with fabric 0.15.0 version. Modrinth set the mod version automatically, I don't think it can be set manually, dunno about CF, but I noticed few mods that updated to Fabric 0.15.0 have mismatched version listed there.
And I know this issue must be fixed, but it just seems it is not caused by our end, by these sites ends.

**Comment by DreenDex** [comment]
I dunno about Modrinth, but on CurseForge you should literally check boxes with compatible versions when uploading by hand in the browser. But on the other hand when doing publishing automatically, the pipeline should care about versions it passes to the CurseForge API (in this case, to the Modrinth API too).

Of course, there are several reasons why this can happen. It can be the owner of this mod, it can be the publishing pipeline. But I don't believe, that it could be CurceForge and/or Modrinth.
The only metadata, that this sites can tell base game version that are supported by this mod, in case of fabric, is `fabric.mod.json` field at path `depends.minecraft`. I really doubt that these services try all uploaded mods automatically on headless Minecraft instances to test if they launch in that game version. Just doesn't make sense. What also doesn't make sense is incorrect display of the base game version on the downloads page, if it based just on mod metadata, which even have specific stable format for it.

Yes, the problem can be with the sites, but its very unlikely to have it on both sites at once.

**Comment by DreenDex** [comment]
> I have a feeling it has something to do with fabric 0.15.0 version

I can't imagine how it can be "0.15.0 version" if you are talking about Fabric Loader, which works in Minecraft's runtime.

Yes, it is an api and is usually included in the mod's compile classpath. But per my knowledge, it doesn't impact any resources exported to the final built mod jar file. Ony Fabric's Loom does it, and in this case, I believe, its Architectury Loom. So to the point of just before mod publishment, the version in the metadata already should be set (or be empty), which it is, and "1.20.2".

Most likely, if it is really a problem with these sites, it could happened _around the date of the release_ of Fabric Loader 0.15.0.

**Comment by Rafii2198** [comment]
Well if you look at that not only Wynntils is affected on Modrinth is really interesting. Especially that we didn't change anything, (the file `fabric.mod.json` you mentioned still only mentions `1.20.2` not something like `>=1.20.2`, only think that have changed is fabric version but minecraft version is untouched, same goes for all projects on modrinth, the version and modloader are autofilled) everything is uploaded automatically, and it worked fine but then suddenly many mods are getting wrong versions, not just Wynntils. To me, it sounds like an issue on Modrinth side, as perhaps their backend started treating `"minecraft": "1.20.2"` same like `"minecraft": ">=1.20.2"`. If it was only Wynntils then yeah, it would seem like an issue on our end, but seeing that Wynntils is just one of many affected mods makes me believe it's on Modrinth's end as again, we didn't change anything regarding the version.

As for Curseforge I have no idea, but I do need to agree it is suspicious that both sites are affected. Can you check if only Wynntils is affected on CF? Because if the situation is same there then it seems they are affected too by similar bug.

Again, **nothing** changed on our end. We will of course look into it regardless as it needs to be fixed. And my comment about Fabric 0.15.0 was just due to coincidence, I checked a few mods that updated to that version of Fabric, and they had mismatched Minecraft version but Forge versions are also affected meaning the Fabric versions has nothing to do with it.

But then again, it could be just a weird coincidence. Perhaps it's the MCPublish at fault, the popular action to publish minecraft projects. Investigation by our devs is needed.

**Comment by magicus** [comment]
@DreenDex 
> developers get paid for downloads.

No, we are not. Wynntils is developed entirely on our spare time. We have a patreon system to finance running our server infrastructure.

I understand that you are frustrated that things are not working, but you are implying that we are making money out of a bug, and that is adding completely unneeded aggressiveness to this bug report. In the future, please take a break before posting such accusations, and think again how what you are writing can be perceived.

**Comment by DreenDex** [comment]
Yes, I see. I apologize for that, it was definitely unnecessary on my part.

Also, in the meantime, i figured out that actually it is likely related to mc-publish (thx to @Rafii2198 to pointing out to it), because I noticed it says `undefined` relative to game-versions fields for curseforge and modrinth in each publishing jobs both for [fabric](https://github.com/Wynntils/Artemis/actions/runs/7140309576/job/19445444542) and [forge](https://github.com/Wynntils/Artemis/actions/runs/7140309576/job/19445444734), so it must generate game versions by itself.
![image](https://github.com/Wynntils/Artemis/assets/6661231/0c7b0acc-3596-4096-83fa-fc3d9e8566f0)

**Comment by Rafii2198** [comment]
I think it should be undefined as when you check the workflow file, there is no explicit definition of a version. Just like MR, mc-publish takes that info from the mod's files when it is not specified. Sadly, logs are only kept for a day I believe and so there is no way of comparing it with the working ones (if they would provide any useful info that is).

**Comment by kristofbolyai** [comment]
This was fixed on newer releases, and we also removed the old 1.20.4 tags.
