### ISSUE TITLE
1.20.4 where

### ISSUE THREAD

**Issue by ghost** [Wynntils/Wynntils#2336]

**Comment by ShadowCat117** [comment]
We aren't currently planning on going to 1.20.4 as there's no benefit for users or us, 1.21 will likely be the next version we go to

**Comment by tunaflsh** [comment]
I just want to leave a comment that it is very beneficial for users. Because for some odd reasons iris shaders didn't fully support 1.20.2 and it's not possible for some shaders and distant horizons to work on 1.20.2.

Looking forward to 1.21 (or 1.21.1 and hopefully it solves the compatibility issues)

**Comment by kristofbolyai** [comment]
It's been already announced how the switch from 1.20.2 to 1.21 and from Wynncraft 2.0 to 2.1 is going to happen on Discord. 1.21 beta versions are already out. 1.20.4 won't have any releases.
