### ISSUE TITLE
GUI scale does not retain its last value when starting in windowed

### ISSUE THREAD

**Issue by Tornado642048** [Wynntils/Wynntils#2816]
What version of the mod are you using? Please include a full version number.
V2.1.1
    What mod loader did you use?
Fabric loader 0.16.2-1.21.1
    Did you use any other mods?
No
    What operating system are you using?
Windows 10
    What did you do?
Start Minecraft
    What did you expect to see?
GUI scale: 3 (because that was what it was last time)
    What did you see instead?
GUI scale: 2

The setting video settings-> gui scale should retain the value it had last time on startup. It does not and always reverts back to 2 even though I set it to 3 last time I closed minecraft. My guess is that windowed mode resets the GUI scale to 2 (only with this mod). When starting minecraft with only fabric installed this issue does not exist.

**Comment by Rafii2198** [comment]
You can work around it by setting initial widnow size to something bigger

**Comment by ShadowCat117** [comment]
I don't think we have an open issue for this so I'll just put it here,

The issue occurs from the following in `FeatureManager`
```
synchronized (McUtils.options()) {
    McUtils.options().load();
}
```

Minecraft checks that the gui scale being set is valid for the current window size, hence if you have a small window you can't go above scale 2. However, the initial load seems to ignore this but since we load the options again, if you have a smaller window size it is lowered to the max fitting scale.

**Comment by kristofbolyai** [comment]
We could save the GUI scale and reapply it then, no?

**Comment by ShadowCat117** [comment]
I think I tried that ages ago when I found the cause and it didn't work, but maybe I went about it wrong
