### ISSUE TITLE
Auto attack feature interrupts macro spell casts

### ISSUE THREAD

**Issue by ShadowCat117** [Wynntils/Wynntils#2936]
`ArmSwingEvent` and `UseItemEvent` are not triggered by our own spell macros or ones by other mods such as [Wynncraft-Spell-Caster](https://github.com/Freeder1k/Wynncraft-Spell-Caster)

**Comment by ShadowCat117** [comment]
@Xaryphon Do you think you would be able to look into this?

**Comment by xaryphon** [comment]
I see three options for this

1. Just add a notice in the feature's config page that you should stop holding attack when quick casting, but people probably won't read it.
2. Test if `QuickCastFeature.SPELL_PACKET_QUEUE` is empty. This is the most accurate one but obviously won't work with other mods and not sure if you want such cross feature accesses. `SPELL_PACKET_QUEUE` is static so a `public static bool isPacketQueueEmpty()` should suffice.
3. Hook the respective packets, but this would share the same edge case as manual casting when starting a second spell cast before we get the completion for the first one leading to `preventWrongCast` being reset. These would probably have to be new events for both packets.

Not sure which one would be the best, maybe a combination or some other way?

**Comment by ShadowCat117** [comment]
Not a fan of option 1, as you say people probably won't read it. Option 2 could work, it's one of those times when I think it's warranted for a feature to access information about another, unless some of the logic was moved somewhere more accessible like `SpellModel` but not really sure it belongs there either. Option 3 could also work.

I'll mention @kristofbolyai to see if they have any different thoughts to mine or another solution.

I did also have a look at the spell caster mod and they have their own hold to attack feature so perhaps users of that mod could simply be recommended to disable the wynntils version

**Comment by kristofbolyai** [comment]
Disable the feature temporarily asap, and we can have a conversation later.

**Comment by Twisted-Code** [comment]
I also don't like option 1, since in my case I am (in order to work around a disability. I'm a quadriplegic gamer!) using voice commands software to press the macro keys. Since it takes a moment for each voice command to resolve, sometimes I don't stop holding the mousebutton at the right moment to avoid interrupting the macro. 
Of course, I don't want the mod to do too much of the thinking for the player (to remain within the spirit of the rules. This is also why I don't use voice commands any more complicated than "press keyname"), but I don't think "release this button before pressing this button" is a difficult thing for most people. I'm just one of the unfortunate exceptions...

**Comment by ShadowCat117** [comment]
Fixed for our spell macros with https://github.com/Wynntils/Wynntils/pull/3021

Won't be fixed for other spell casting mods
