### ISSUE TITLE
Color vs Colour

### ISSUE THREAD

**Issue by Incompleteusern** [Wynntils/Wynntils#381]
Precedent states that british english is used, and thus "colour" is preferred in settings? Internally, and I am partially responsible this, however, "color" is used interchangeably. It might be nice to replace all appearances with "colour", or vice versa in the code base.

**Comment by magicus** [comment]
I'd say go for "color". As a non-native English speaker, I know I tend to mix e.g. "behaviour" and "behavior" frequently. But when it comes to programming, "color" is kind of well-established. For better or for worse, I think we should try to stick to "simplified English" instead of "traditional English" [as defined by Steam](https://external-preview.redd.it/onUp1ux80oXCQL25c_dplRHnyGaim5eUmC7NpvXxKvI.jpg?auto=webp&s=9158337578aa48094051c9163bc9818339451d7a).
