### ISSUE TITLE
Mini map overlay does not respect it's size

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#463]
![image](https://user-images.githubusercontent.com/49001742/192526496-e6861e16-fefa-4a8b-b7a8-98388cb0007d.png)
![image](https://user-images.githubusercontent.com/49001742/192526517-eefceaa6-d64c-4d63-aeab-e8dfd8d54d18.png)

As seen, coordinates are rendered outside of the render area.

**Comment by HighCrit** [comment]
I feel like those should be removed and people should use the info overlays for coordinates.

**Comment by magicus** [comment]
Another problem is that the cardinal markers are partially outside (S and W are cut in half in the image). This can "easily" be fixed by moving this rendering more in towards the middle. I've been thinking about filing a bug but always forgetting it, so I'm hijacking this slightly to expand the purpose. :)

Coordinates are trickier. I really like the coordinates below the map. Having to create a separate info overlay and position it nicely next to the map seems like a regression. 

Still, I see the point. If we really do consider this as part of the overlay, then the overlay outline stops being square, which might look odd. And if we make coordinates toggleable (don't know if they already are), then for someone who do not want coordinates, they'll have to deal with a non-square outline, that then doesn't match what they see.

What if we let MiniMapFeature define two overlays? MiniMapOverlay and MiniMapCoordinatesOverlay? Can we add functionality to "connect" overlays, so if we move the map, the coordinates follow along?

**Comment by kristofbolyai** [comment]
I just though about adding something like connected overlays where rendering position is based on the other. I just do not see that many use cases atm.

**Comment by magicus** [comment]
This is likely to be one of the few cases, yes. Perhaps for info boxes as well?

**Comment by kristofbolyai** [comment]
Yeah info boxes will overflow vertically, but not horizontally.

**Comment by magicus** [comment]
But I understand if it's much work to do to fix just this one behavior. Hm. Maybe. What if a single overlay could have like separate parts? So when drawing the overlay there was an additional line showing the split between map and coordinates? I think that would help make it clear how it will be rendered?

Or we skip over-engineering this alltogether, and just fixes the outline for the minimap to match what it actually renders.

**Comment by Incompleteusern** [comment]
> ![image](https://user-images.githubusercontent.com/49001742/192526496-e6861e16-fefa-4a8b-b7a8-98388cb0007d.png) ![image](https://user-images.githubusercontent.com/49001742/192526517-eefceaa6-d64c-4d63-aeab-e8dfd8d54d18.png)
> 
> As seen, coordinates are rendered outside of the render area.

Yeah, the cause of this is that coordinate code was tacked on without concern for this.

**Comment by Incompleteusern** [comment]
> > ![image](https://user-images.githubusercontent.com/49001742/192526496-e6861e16-fefa-4a8b-b7a8-98388cb0007d.png) ![image](https://user-images.githubusercontent.com/49001742/192526517-eefceaa6-d64c-4d63-aeab-e8dfd8d54d18.png)
> > As seen, coordinates are rendered outside of the render area.
> 

Yeah, the cause of this is that coordinate code was tacked on without concern for this. How we fix this seems to be a decent concern, especially without text scaling.

**Comment by kristofbolyai** [comment]
Fixed now.
